### ISSUE TITLE
Mark certain tags as "Do not Purge"

### ISSUE THREAD

**Issue by runevad** [PrevasAutArch/AutArchCustomer#18] opened 2018-09-06 05:51 UTC
I would like the ability to mark certain TAGs as "DNP" meaning "do not purge" from the DB. 
This would help when having some measurements that need to be stored for longer periods for legal reasons, like for example emissions, power output, etc.  
This way the rest of the DB can be purged as normal in order to keep it snappy. 
#FeatureRequestBackend

**Comment by runevad** [comment] 2018-09-06 06:08
I missade the #11 as it was closed before. Is this Fixed?

**Comment by LinusEvertsson** [comment] 2018-09-06 06:10
Duplicate of #11 
This has been implemented in issue 11 and will be released in v3.4.0.

I realised that closed issues are harder to find and have therefore opened all issues related to 3.4.0 and added the label "Fixed".
These issues will be kept open until v3.4.0 is officially released.

**Closed** 2018-09-06 06:11 UTC
Labels: duplicate
